application: gui-cn-hrd
version: 3
runtime: python
api_version: 1

handlers:
- url: /((characterIssue)|(DevNotes)).html
  script: redirect.py
  
- url: /
  static_files: index.html
  upload: index.html

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  
- url: /javascripts
  static_dir: javascripts
 
- url: /res/FortuneTeller.wgz
  static_files: res/FortuneTeller.wgz
  upload: res/FortuneTeller.wgz
  mime_type: application/x-nokia-widget

- url: /.*
  script: myApp.py
